spring.application.name=backend-spring

# H2 Database configuration - save to file to persist across restarts
spring.datasource.url=jdbc:h2:file:./data/catsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-bean-definition-overriding=true
